### ISSUE TITLE
Add the "Norwegian" language

### ISSUE THREAD

**Issue by tobiasvl** [snorremd/norsky#18]
Bluesky has a language option that's just "Norwegian" as well, with ISO 639 language code `no`. Without it, this feed is probably missing a lot of Norwegian posts.

**Comment by snorremd** [comment]
Hmmm, I actually think this is handled already by the firehose logic including posts tagged with language code `no`.

```
if lo.Some(post.Langs, []string{"no", "nb", "nn", "se"}) {
```

In the "Norwegian Languages" feed there is no filter on language, so it should return all posts tagged with either of the language codes listed above.

**Comment by tobiasvl** [comment]
Aha, hmm! Maybe you're correct, I must have misunderstood how the firehose worked and how it was filtered by language in `genericAlgo()`...

**Comment by snorremd** [comment]
Closing as solved. 👍
